### PR TITLE
Add docs for new systemd feature 'RuntimeDirectory=uwsgi'

### PR DESCRIPTION
**Pull request by jeffwidman**

### CODE REVIEW

**Comment by jeffwidman** [comment]
Fixed version of https://github.com/unbit/uwsgi-docs/pull/253 - I accidentally deleted the source repo for that PR, so couldn't amend it and had to create a new PR.

**Comment by xrmx** [comment]
Thanks for updating, merged.

**Comment by kylegibson** [comment]
I followed this documentation, and the result was the following:

```
:~ $ ls -l /run/
total 28
drwxr-xr-x 2 root  root     40 Feb  7 00:49 #
drwxr-xr-x 2 root  root     40 Feb  7 00:49 211
drwxr-xr-x 2 avahi avahi    80 Feb  6 21:17 avahi-daemon
-rw-r--r-- 1 root  root      4 Feb  6 21:17 crond.pid
---------- 1 root  root      0 Feb  6 21:17 crond.reboot
drwxr-xr-x 2 root  root     60 Feb  6 21:17 dbus
lrwxrwxrwx 1 root  root     25 Feb  6 21:17 initctl -> /run/systemd/initctl/fifo
drwxrwxrwt 4 root  root    100 Feb  6 21:17 lock
drwxr-xr-x 3 root  root     60 Feb  6 21:17 log
drwxr-xr-x 2 root  root     60 Feb  6 21:17 mount
drwxr-xr-x 2 mysql root     80 Feb  6 21:19 mysqld
drwxr-xr-x 2 root  netdev   80 Feb  6 21:17 network
drwxr-xr-x 2 root  root     40 Feb  7 00:49 newer
-rw-r--r-- 1 root  root      5 Feb  6 21:22 nginx.pid
-rw-r--r-- 1 root  root      3 Feb  6 21:17 ntpd.pid
drwxr-xr-x 2 root  root     40 Feb  7 00:49 or
drwxrwsr-x 2 redis redis    60 Feb  6 21:17 redis
drwxr-xr-x 2 root  root     40 Feb  7 00:49 Requires
-rw-r--r-- 1 root  root      4 Feb  6 21:17 rsyslogd.pid
drwxrwxr-x 3 root  utmp     60 Feb  7 00:13 screen
drwxr-xr-x 2 root  root     40 Feb  6 21:17 sendsigs.omit.d
lrwxrwxrwx 1 root  root      8 Feb  6 21:17 shm -> /dev/shm
drwxr-xr-x 2 root  root     40 Feb  6 21:17 sshd
-rw-r--r-- 1 root  root      4 Feb  6 21:17 sshd.pid
drwxr-xr-x 6 root  root    120 Feb  7 00:50 systemd
-rw-r--r-- 1 root  root      4 Feb  6 21:17 thd.pid
srwxr-xr-x 1 root  root      0 Feb  6 21:17 thd.socket
drwxr-xr-x 2 root  root     60 Dec 31  1969 tmpfiles.d
drwxr-xr-x 7 root  root    160 Feb  6 21:17 udev
drwxr-xr-x 2 root  root     40 Feb  6 21:17 user
-rw-rw-r-- 1 root  utmp   2688 Feb  7 00:44 utmp
drwxr-xr-x 2 root  root     40 Feb  7 00:49 uwsgi
drwxr-xr-x 2 root  root     40 Feb  7 00:49 version
```

Notice that there are a few odd directories: `#`, `Requires`, `211`, `or`, `newer`. It appears that the inline comment is not ignored.

**Comment by xrmx** [comment]
@kylegibson thanks, fix pushed!

**Comment by jeffwidman** [comment]
Thanks. For future reference, fix is 20ecd37ba06b6710dc28f291bca54d84175d9945

**Pull request merged**
