### PR TITLE
Make stats-http more obvious by adding individual code sample.

### PR DESCRIPTION
**Pull request by edwelker**
Between https://github.com/unbit/uwsgi/issues/834 and myself overlooking the stats-http setting, I think it would be beneficial to include a separate example.

### CODE REVIEW

**Comment by edwelker** [comment]
Updated.  Let me know what you think.

**Comment by edwelker** [comment]
Done.

**Comment by xrmx** [comment]
@edwelker thanks! will squash commit and merge next tuesday!

**Comment by edwelker** [comment]
No, thank you. :)

**Comment by edwelker** [comment]
No, thank you. :)

**Comment by xrmx** [comment]
Merged, thanks!

**Pull request closed without merging**
