### PR TITLE
Update Snippets.rst

### PR DESCRIPTION
**Pull request by reinow**
Add SELinux snippet to Snippets.rst

### CODE REVIEW

**Comment by akx** [comment]
Good stuff. This might be nice to have in a page of its own to be honest!

**Comment by unbit** [comment]
Aren't you missing reference to the setcon hook ? i suppose a plugin or a shared library is required for it

**Comment by akx** [comment]
> `int setcon(security_context_t context);`

`security_context_t` is an typedef for `char`, so so long as `callret` expects something like `int X(const char *p)` as the argument's calling convention, this should work, I think?

**Comment by reinow** [comment]
On my Centos7 boxes libselinux.so is loaded by default, so --dlopen /path/libselinux.so is not required. Do you think we should add the dlopen option anyway, to make sure libselinux is loaded in the uwsgi address space?

**Comment by unbit** [comment]
I think you should mention how it works (calling a function of libselinux) and it could be required to load it with --dlopen

**Comment by reinow** [comment]
I posted a new patch 6 days ago. Feedback is welcome.

**Comment by unbit** [comment]
All is fine, thanks

**Pull request merged**
