### PR TITLE
Use b"Hello, World" on PY2

### PR DESCRIPTION
**Pull request by methane**
Using `b` prefix for bytes is preferred on PY2, too.

### CODE REVIEW

**Comment by unbit** [comment]
Not completely sure about it, maybe @GrahamDumpleton could give an opinion ?

**Comment by GrahamDumpleton** [comment]
Makes it work for both Python 2 and 3 so don't see an issue.

My own test example I always use is:

```
def application(environ, start_response):
    status = '200 OK'
    output = b'Hello World!'

    response_headers = [('Content-type', 'text/plain'),
                        ('Content-Length', str(len(output)))]
    start_response(status, response_headers)

    return [output]
```

Don't pay attention to mod_wsgi docs though as they are very out of date. :-)

**Comment by methane** [comment]
See here: https://www.python.org/dev/peps/pep-3333/#the-application-framework-side

**Comment by unbit** [comment]
Ok, seems the right thing to do. Thanks a lot

**Pull request merged**
