### PR TITLE
Add docs for new systemd feature 'RuntimeDirectory=uwsgi'

### PR DESCRIPTION
**Pull request by jeffwidman**
Per http://unix.stackexchange.com/a/209368/87956

### CODE REVIEW

**Comment by jeffwidman** [comment]
Anything else needed to merge this?

**Comment by xrmx** [comment]
The changes looks fine, do you know how "relatively new" is this feature, as in which systemd version has been introduced?

**Comment by jeffwidman** [comment]
Sorry, no idea how new... I just saw the stackoverflow answer and thought I'd add a note in the relevant uWSGI docs

**Comment by xrmx** [comment]
@jeffwidman regarding systemd version, which systemd are you using that have this feature? if debian stable / rhel 7 has it we can apply your patch otherwise i think it would be better to just apply the second hunk.

**Comment by jeffwidman** [comment]
Not sure I see a reason to drop the first hunk, assuming that Systemd just silently ignores it if it's not supported... haven't tested it, but if that's the case, then we lose nothing by leaving it there, and it's useful for those on newer systemd releases. 

I'll have to look at what systemd version I'm using on my uWSGI server.

**Comment by xrmx** [comment]
The reason is to don't think that your system is doing a thing because you think it is configured to do so when in fact it does not. We can keep it if we add an "available since" comment.

**Comment by jeffwidman** [comment]
Continued in https://github.com/unbit/uwsgi-docs/pull/263 - I accidentally deleted the source repo for this PR, so couldn't amend it and had to create a new PR.

**Pull request closed without merging**
