### PR TITLE
Document cache_set and cache_update

### PR DESCRIPTION
**Pull request by svenstaro**
It wasn't exactly clear before how these differ.

### CODE REVIEW

**Comment by svenstaro** [comment]
On a related note, why is the last parameter for cache_update `cache_server` but for all the other caching functions it's `cache_name`?

**Comment by smontanaro** [comment]
In a thread I started on the mailing list, it was confirmed that it should be "cache_name". You could probably amend your PR to correct that error.

**Comment by svenstaro** [comment]
@smontanaro done

**Comment by xrmx** [comment]
Merged, thanks

**Pull request merged**
